---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: otel
data:
  config.yaml: |-
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
            # tls:
            #   insecure: true
          # http:
            # endpoint: 0.0.0.0:55681
            # tls:
            #   insecure: true
      hostmetrics:
        collection_interval: 1m
        scrapers:
          cpu:
          load:
          memory:

    processors:
      batch: 
        timeout: 1m

    exporters:
      elastic:
        apm_server_url: 'http://192.168.0.147:31436'
      jaeger:
        endpoint: "http://192.168.0.147:32427" 
        tls:
          insecure: true

      logging:
        loglevel: DEBUG

    extensions:
      health_check:

    service:
      pipelines:

        metrics:
          receivers:
            - otlp
            - hostmetrics
          exporters:
            - logging
            - elastic

        traces:
          receivers:
            - otlp

          processors:
            - batch
            
          exporters:
            - elastic
            - jaeger
            - logging
