apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  ports:
  - name: metrics # Default endpoint for querying metrics.
    port: 8888
  - name: grpc # Default endpoint for OpenTelemetry receiver.
    port: 55680
    protocol: TCP
    targetPort: 55680
  - name: http # Default endpoint for OpenTelemetry receiver.
    port: 55681
    protocol: TCP
    targetPort: 55681
  selector:
    component: otel-collector
  sessionAffinity: None
  type: NodePort